name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup signing
        if: github.event_name == 'push' && github.repository_owner == 'nyaruta'
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks
          {
            echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}"
            echo "keyPassword=${{ secrets.KEY_PASSWORD }}"
            echo "keyAlias=${{ secrets.KEY_ALIAS }}"
            echo "storeFile=${{ github.workspace}}/keystore.jks"
          } > key.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            app/debug/*.apk
            app/release/*.apk

      